CREATE TABLE IF NOT EXISTS APIKeys(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    Name TEXT NOT NULL,
    KeyHash TEXT UNIQUE NOT NULL,
    CreatedAt INTEGER DEFAULT(unixepoch()),
    FOREIGN KEY(UserId) REFERENCES users(ID)
);
