CREATE TABLE IF NOT EXISTS Tokens(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    TokenHash TEXT UNIQUE NOT NULL,
    CreatedAt INTEGER DEFAULT(unixepoch()),
    FOREIGN KEY(UserID) REFERENCES users(ID)
);
